### ISSUE TITLE
errors with docker-compose up

### ISSUE THREAD

**Issue by sanyaade-teachings** [liudonghua123/dart-pad-docker#1]
Hello @liudonghua123 :

Many thanks for your dart-pad-docker stack.

I used your files try to implement the dart-pad on docker engine. The images was built but then I had two error relating to the services and running.

Please see below docker-compose terminal messages

`[sanyaade@ns1 dart-pad-docker]$ docker-compose up
Starting dart-pad-docker_dart-pad_1      ... done
Starting dart-pad-docker_dart-services_1 ... done
Attaching to dart-pad-docker_dart-services_1, dart-pad-docker_dart-pad_1
dart-services_1  | Resolving dependencies...
dart-services_1  |   _discoveryapis_commons 0.1.9 (1.0.0 available)
dart-services_1  |   analysis_server_lib 0.1.8 (0.1.10 available)
dart-services_1  |   analyzer 0.38.5 (1.1.0 available)
dart-services_1  |   appengine 0.10.4 (0.12.0 available)
dart-services_1  |   args 1.5.2 (2.0.0 available)
dart-services_1  |   async 2.4.0 (2.5.0 available)
dart-services_1  |   bazel_worker 0.1.23 (1.0.0 available)
dart-services_1  |   boolean_selector 1.0.5 (2.1.0 available)
dart-services_1  |   charcode 1.1.2 (1.2.0 available)
dart-services_1  |   cli_util 0.1.3+2 (0.3.0 available)
dart-services_1  |   codemirror 0.5.12+5.49.2 (0.5.24+5.59.2 available)
dart-services_1  |   collection 1.14.12 (1.15.0 available)
dart-services_1  |   convert 2.1.1 (3.0.0 available)
dart-services_1  |   coverage 0.13.3+3 (1.0.1 available)
dart-services_1  |   crypto 2.1.4 (3.0.0 available)
dart-services_1  |   csslib 0.16.1 (0.17.0 available)
dart-services_1  |   dart_style 1.3.3 (1.3.14 available)
dart-services_1  |   dartis 0.3.0 (0.5.0 available)
dart-services_1  |   discoveryapis_generator 0.9.11 (0.9.15 available)
dart-services_1  |   fixnum 0.10.11 (1.0.0 available)
dart-services_1  |   front_end 0.1.27 (discontinued)
dart-services_1  |   gcloud 0.6.3 (0.7.3 available)
dart-services_1  |   glob 1.2.0 (2.0.0 available)
dart-services_1  |   googleapis 0.54.0 (2.0.0 available)
dart-services_1  |   googleapis_auth 0.2.11 (1.1.0 available)
dart-services_1  |   grinder 0.8.3+1 (0.8.6 available)
dart-services_1  |   grpc 2.1.3 (3.0.0 available)
dart-services_1  |   html 0.14.0+3 (0.15.0 available)
dart-services_1  |   http 0.12.0+2 (0.13.0 available)
dart-services_1  |   http2 1.0.0 (2.0.0 available)
dart-services_1  |   http_multi_server 2.1.0 (3.0.0 available)
dart-services_1  |   http_parser 3.1.3 (4.0.0 available)
dart-services_1  |   intl 0.15.8 (0.17.0 available)
dart-services_1  |   io 0.3.3 (1.0.0 available)
dart-services_1  |   js 0.6.1+1 (0.6.3 available)
dart-services_1  |   kernel 0.3.27 (discontinued)
dart-services_1  |   logging 0.11.3+2 (1.0.0 available)
dart-services_1  |   matcher 0.12.6 (0.12.10 available)
dart-services_1  |   meta 1.1.8 (1.3.0 available)
dart-services_1  |   mime 0.9.6+3 (1.0.0 available)
dart-services_1  |   multi_server_socket 1.0.2 (discontinued)
dart-services_1  |   node_interop 1.0.3 (1.2.1 available)
dart-services_1  |   node_io 1.0.1+2 (1.2.0 available)
dart-services_1  |   node_preamble 1.4.8 (2.0.0 available)
dart-services_1  |   package_config 1.1.0 (2.0.0 available)
dart-services_1  |   package_resolver 1.0.10 (discontinued)
dart-services_1  |   path 1.6.4 (1.8.0 available)
dart-services_1  |   pedantic 1.9.0 (1.11.0 available)
dart-services_1  |   pool 1.4.0 (1.5.0 available)
dart-services_1  |   protobuf 1.0.1 (2.0.0 available)
dart-services_1  |   pub_semver 1.4.2 (2.0.0 available)
dart-services_1  |   quiver 2.1.2+1 (3.0.0 available)
dart-services_1  |   rpc 0.6.2 (discontinued)
dart-services_1  |   shelf 0.7.5 (1.0.0 available)
dart-services_1  |   shelf_packages_handler 1.0.4 (3.0.0 available)
dart-services_1  |   shelf_static 0.2.8 (1.0.0 available)
dart-services_1  |   shelf_web_socket 0.2.3 (1.0.0 available)
dart-services_1  |   source_map_stack_trace 1.1.5 (2.1.0 available)
dart-services_1  |   source_maps 0.10.8 (0.10.10 available)
dart-services_1  |   source_span 1.5.5 (1.8.1 available)
dart-services_1  |   stack_trace 1.9.3 (1.10.0 available)
dart-services_1  |   stream_channel 2.0.0 (2.1.0 available)
dart-services_1  |   string_scanner 1.0.5 (1.1.0 available)
dart-services_1  |   synchronized 2.1.1 (3.0.0 available)
dart-services_1  |   term_glyph 1.1.0 (1.2.0 available)
dart-services_1  |   test 1.9.4 (1.16.7 available)
dart-services_1  |   test_api 0.2.11 (0.3.0 available)
dart-services_1  |   test_core 0.2.15 (0.3.18 available)
dart-services_1  |   tuneup 0.3.6+1 (0.3.7 available)
dart-services_1  |   typed_data 1.1.6 (1.3.0 available)
dart-services_1  |   uri 0.11.3+1 (1.0.0 available)
dart-services_1  |   utf 0.9.0+5 (discontinued)
dart-services_1  |   uuid 2.0.4 (3.0.1 available)
dart-services_1  |   vm_service 2.1.4 (6.1.0+1 available)
dart-services_1  |   watcher 0.9.7+13 (1.0.0 available)
dart-services_1  |   web_socket_channel 1.1.0 (2.0.0 available)
dart-services_1  |   yaml 2.2.0 (3.1.0 available)
dart-services_1  | Got dependencies!
dart-pad_1       | grinder running build serve-custom-backend
dart-pad_1       | 
dart-pad_1       | build
dart-pad_1       |   /usr/lib/dart/bin/pub run build_runner build -r -o web:build
dart-pad_1       |   Unhandled exception:
dart-pad_1       |   RangeError: Value not in range: -1
dart-pad_1       |   #0      _StringBase.substring (dart:core-patch/string_patch.dart:399:7)
dart-pad_1       |   #1      _parsePackageLocations (package:build_runner_core/src/package_graph/package_graph.dart:162:21)
dart-pad_1       |   #2      new PackageGraph.forPath (package:build_runner_core/src/package_graph/package_graph.dart:67:30)
dart-pad_1       |   #3      new PackageGraph.forThisPackage (package:build_runner_core/src/package_graph/package_graph.dart:98:57)
dart-pad_1       |   #4      new BuildCommandRunner (package:build_runner/src/entrypoint/runner.dart:27:37)
dart-pad_1       |   #5      main (file:///root/.pub-cache/hosted/pub.dartlang.org/build_runner-1.7.4/bin/build_runner.dart:25:23)
dart-pad_1       |   #6      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:281:32)
dart-pad_1       |   #7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
dart-pad_1       | 
dart-pad_1       | failed with exit code 255
dart-pad_1       | #0      run (package:grinder/src/run.dart:48:5)
dart-pad_1       | #1      Pub.run (package:grinder/grinder_sdk.dart:241:12)
dart-pad_1       | #2      _PubLocalApp.run (package:grinder/grinder_sdk.dart:583:16)
dart-pad_1       | #3      build (file:///dart-pad/tool/grind.dart:132:32)
dart-pad_1       | #4      _LibraryMirror._invoke (dart:mirrors-patch/mirrors_impl.dart:984:36)
dart-pad_1       | #5      _ObjectMirror.invoke (dart:mirrors-patch/mirrors_impl.dart:242:25)
dart-pad_1       | #6      TaskDiscovery.discoverDeclaration.<anon> (package:grinder/src/discover_tasks.dart:79:38)
dart-pad_1       | #7      _rootRun (dart:async/zone.dart:1354:13)
dart-pad_1       | #8      _CustomZone.run (dart:async/zone.dart:1258:19)
dart-pad_1       | #9      _runZoned (dart:async/zone.dart:1788:10)
dart-pad_1       | #10     runZoned (dart:async/zone.dart:1710:10)
dart-pad_1       | #11     ZonedValue.withValue (package:grinder/src/utils.dart:112:12)
dart-pad_1       | #12     GrinderTask.execute (package:grinder/src/grinder_task.dart:63:27)
dart-pad_1       | #13     Grinder._invokeTask (package:grinder/src/grinder.dart:193:27)
dart-pad_1       | #14     Grinder.start.<anon> (package:grinder/src/grinder.dart:168:16)
dart-pad_1       | #15     Future.forEach.<anon> (dart:async/future.dart:495:26)
dart-pad_1       | #16     Future.doWhile.<anon> (dart:async/future.dart:535:26)
dart-pad_1       | #17     _RootZone.runUnaryGuarded (dart:async/zone.dart:1546:10)
dart-pad_1       | #18     _RootZone.bindUnaryCallbackGuarded.<anon> (dart:async/zone.dart:1585:26)
dart-pad_1       | #19     Future.doWhile (dart:async/future.dart:551:18)
dart-pad_1       | #20     Future.forEach (dart:async/future.dart:493:12)
dart-pad_1       | #21     Grinder.start (package:grinder/src/grinder.dart:167:21)
dart-pad_1       | #22     runTasks (package:grinder/src/cli.dart:67:39)
dart-pad_1       | #23     grind (package:grinder/grinder.dart:46:12)
dart-pad_1       | #24     main (file:///dart-pad/tool/grind.dart:23:28)
dart-pad-docker_dart-pad_1 exited with code 1
dart-services_1  | Unhandled exception:
dart-services_1  | FileSystemException: Cannot open file, path = '/dart-services/flutter/bin/cache/dart-sdk/version' (OS Error: No such file or directory, errno = 2)
dart-services_1  | #0      _File.open.<anonymous closure> (dart:io/file_impl.dart:356:9)
dart-services_1  | #1      _RootZone.runUnary (dart:async/zone.dart:1612:54)
dart-services_1  | #2      _FutureListener.handleValue (dart:async/future_impl.dart:152:18)
dart-services_1  | #3      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:704:45)
dart-services_1  | #4      Future._propagateToListeners (dart:async/future_impl.dart:733:32)
dart-services_1  | #5      Future._completeWithValue (dart:async/future_impl.dart:539:5)
dart-services_1  | #6      Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:577:7)
dart-services_1  | #7      _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
dart-services_1  | #8      _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
dart-services_1  | #9      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:120:13)
dart-services_1  | #10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:185:5)
dart-pad-docker_dart-services_1 exited with code 255
[sanyaade@ns1 dart-pad-docker]$ 
`
1.) error from the above:
dart-pad_1       |   /usr/lib/dart/bin/pub run build_runner build -r -o web:build
dart-pad_1       |   Unhandled exception:
dart-pad_1       |   RangeError: Value not in range: -1

2.) error from the above is:
dart-services_1  | Unhandled exception:
dart-services_1  | FileSystemException: Cannot open file, path = '/dart-services/flutter/bin/cache/dart-sdk/version' (OS Error: No such file or directory, errno = 2)

Looks like file path for dark-sdk inside the container

Have you come across these errors?

Please help!

Hear from you soon!

God blesses!!!

Best regards,
Sanyaade

**Comment by liudonghua123** [comment]
@sanyaade-teachings Hi, I updated the code, now you can try again. You need to change `docker-compose.yml` according to your own environment.

**Comment by sanyaade-teachings** [comment]
@liudonghua123 : 

Many thanks for your support,  for the efforts and taken time to update the code.

I will try it again and I will make changes to the docker-compose.yml

Do I need a domain or can I run it locally on my server first?
I see the you have the environmental values for VIRTUAL_HOST:
environment:
      - VIRTUAL_HOST=dart-pad.api.ynu.edu.cn
    entrypoint: bash -c "cd /dart-pad && DARTPAD_BACKEND=http://dart-services.api.ynu.edu.cn grind serve-custom-backend"

For example I have a domain (**skillmender.com**) with a Centos-7 server which is where I did the initial test.
How do I change it to e.g. **dart-pad.api.skillmender.com** (which file do I need to make this changes or I just do it inside the docker-compose.yml)? Many thanks.

If I ran into problems again, please I will ask for your help.

Once again many thanks for all your support. Much appreciated!

God blesses!!!

Best regards,
Sanyaade

**Comment by sanyaade-teachings** [comment]
@liudonghua123 :+1: 

Many thanks! It is working now and accessible through port: 48156 on my localhost.

I tried all the examples and they work as well but no flutter code work.
I also changed the virtualhost to point to my domain with no problems.

I now need to know how to get flutter to run on it.

Many thanks! Much appreciated.

I will close this issue now.
Many thanks!

God blesses!!!

Best regards,
Sanyaade

**Comment by liudonghua123** [comment]
> @liudonghua123 :
> 
> Many thanks for your support, for the efforts and taken time to update the code.
> 
> I will try it again and I will make changes to the docker-compose.yml
> 
> Do I need a domain or can I run it locally on my server first?
> I see the you have the environmental values for VIRTUAL_HOST:
> environment:
> - VIRTUAL_HOST=dart-pad.api.ynu.edu.cn
> entrypoint: bash -c "cd /dart-pad && DARTPAD_BACKEND=http://dart-services.api.ynu.edu.cn grind serve-custom-backend"
> 
> For example I have a domain (**skillmender.com**) with a Centos-7 server which is where I did the initial test.
> How do I change it to e.g. **dart-pad.api.skillmender.com** (which file do I need to make this changes or I just do it inside the docker-compose.yml)? Many thanks.
> 
> If I ran into problems again, please I will ask for your help.
> 
> Once again many thanks for all your support. Much appreciated!
> 
> God blesses!!!
> 
> Best regards,
> Sanyaade

@sanyaade-teachings Hi, I use `VIRTUAL_HOST` to simplify the deployment process. You can find more on https://github.com/nginx-proxy/nginx-proxy, To deploy your own dart-pad, you need two web services, one for the frontend, and another for the backend. 

I will try to write a README for more detailed documentation and combine both the frontend and the backend to simplify the deployment.

> I tried all the examples and they work as well but no flutter code work.

That's really strange, I can get flutter to run on my environment. Maybe you should wait for a while (about 10~20 seconds) to make dart-services compile and send the response.

And start the dart-services container needs time to do some initial work like update-sdk.

![image](https://user-images.githubusercontent.com/2276718/111092987-a4a56200-8572-11eb-81ab-ede8caf2f81e.png)

**Comment by sanyaade-teachings** [comment]
@liudonghua123  : 

Many thanks for the update and for show an example.
I will see if I can get flutter to work tonight following your examples and steps.

I will get back to you on the flutter side of things as well.

once again many thanks!
Hear from you soon!

God blesses!!!

Best regards,
Sanyaade
